import { StyleSheet } from "react-native";
import { Dimensions } from "react-native/Libraries/Utilities/Dimensions";
import { useTheme } from "../../theme";

export default function styles(mode: "light" | "dark") {
    const theme = useTheme(mode);
    return StyleSheet.create({
        carouselPaginationContainer: {
            position: "absolute",
            bottom: 0,
            flexDirection: "row",
            width: "100%",
            alignItems: "center",
            justifyContent: "center",
        },
        carouselPaginationDotWide: {
            width: 24,
            height: 8,
            borderRadius: 4,
            marginHorizontal: 2,
        },
        carouselPaginationDotRegular: {
            width: 8,
            height: 8,
            borderRadius: 4,
            marginHorizontal: 2,
        },
        carouselSlideContainer: {
            paddingHorizontal: 30,
        },
        carouselSlideContent: {},
        carouselSlideTitle: {
            margin: 3,
            color: theme.options.colors.background[500],
            textAlign: "left",
        },
        carouselSlideText: {
            marginTop: 20,
            marginHorizontal: 3,
            color: theme.options.colors.background[500],
            textAlign: "left",
        },
        logo: {
            marginVertical: 20,
            color: theme.options.colors.background[500],
        },
        container: {
            flex: 1,
            alignItems: "center",
        },
        heroVideoContainer: {
            position: "absolute",
            top: 0,
            left: 0,
            right: 0,
            bottom: 0,
            flex: 1,
            zIndex: -2,
            justifyContent: "center",
            alignItems: "center",
        },
        backdrop: {
            position: "absolute",
            top: 0,
            left: 0,
            right: 0,
            bottom: 0,
            flex: 1,
            zIndex: -1,
            justifyContent: "center",
            alignItems: "center",
            backgroundColor: "black",
            opacity: 0.3,
        },
        sheetShadow: {
            position: "absolute",
            zIndex: -1,
            backgroundColor: theme.options.colors.background[500],
            borderTopLeftRadius: 50,
            borderTopRightRadius: 50,
            shadowOpacity: 0.5,
            shadowRadius: 40,
            shadowOffset: { width: 0, height: -50 },
        },
        sheetContainer: {
            position: "absolute",
            zIndex: 1,
            backgroundColor: theme.options.colors.background[500],
            borderTopLeftRadius: 50,
            borderTopRightRadius: 50,
            paddingHorizontal: 40,
            paddingTop: 40,
            alignItems: "center",
        },
        sheetTitleContainer: {
            width: "100%",
            justifyContent: "space-between",
            alignItems: "center",
            flexDirection: "row",
            flexWrap: "nowrap",
            marginBottom: 15,
        },
        sheetSubtitleContainer: {
            width: "100%",
            justifyContent: "space-between",
            alignItems: "center",
            flexDirection: "row",
            flexWrap: "nowrap",
            marginBottom: 30,
        },
        sheetAutoCompleteInputContainer: {
            width: "100%",
            justifyContent: "space-between",
            alignItems: "center",
            flexDirection: "row",
            flexWrap: "nowrap",
            marginBottom: 20,
        },
        sheetTextInputTitle: {
            position: "absolute",
            fontSize: 16,
            zIndex: 1,
            top: 20,
            left: 20,
        },
        sheetTextInputContainer: {
            width: "100%",
            height: 100,
            paddingHorizontal: 20,
            paddingTop: 30,
            flexDirection: "row",
            flexWrap: "nowrap",
            backgroundColor: theme.options.colors.text[300],
            borderWidth: 1,
            borderRadius: 20,
            shadowRadius: 20,
            shadowOpacity: 0.08,
            shadowOffset: { width: 0, height: 10 },
        },
        sheetTextInput: {
            flex: 1,
            color: theme.options.colors.text[400],
        },
        sheetHeroImageContainer: {
            width: 90,
            height: 90,
            backgroundColor: theme.options.colors.background[400],
            borderRadius: 45,
            justifyContent: "center",
            alignItems: "center",
        },
        sheetHeroImage: {
            width: 80,
            height: 80,
        },
    });
}
